name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Debug workspace
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Dist directory contents (if exists):"
          ls -la dist || echo "dist directory not found"
          echo "Current working directory:"
          pwd

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: dist
          if-no-files-found: error

      - name: Verify artifact upload
        run: echo "Artifact upload step completed"

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Debug before download
        run: |
          echo "Current directory before download:"
          ls -la
          pwd

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: dist

      - name: Debug after download
        run: |
          echo "Current directory after download:"
          ls -la
          echo "Dist directory contents:"
          ls -la dist || echo "dist directory not found"
          pwd

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          force_orphan: true
