name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci  # Recommended over npm install for CI environments

      - name: Build project
        run: npm run build

      - name: Extensive Debug of Build Output
        run: |
          echo "Build output directory contents:"
          find . -maxdepth 2 -type d
          echo "Checking potential build directories:"
          ls -la build || echo "No 'build' directory"
          ls -la dist || echo "No 'dist' directory"
          ls -la out || echo "No 'out' directory"

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          # Try multiple potential build directories
          path: |
            build
            dist
            out
          if-no-files-found: error

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files

      - name: Debug after artifact download
        run: |
          echo "Contents after artifact download:"
          ls -la
          echo "Checking subdirectories:"
          find . -maxdepth 2 -type d

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Changed from 'dist' to current directory
          publish_branch: gh-pages
          force_orphan: true
